baseURL = 'https://CAF-Expert.github.io/caffezeit-org/'
languageCode = 'de-de'
title = 'CAFfe Zeit'
theme = 'PaperMod'

# Erweiterte Konfiguration
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

# Syntax Highlighting - Clean Theme
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
  # Main Sections für Startseite definieren
  mainSections = ["posts"]
  
  # Allgemeine Einstellungen
  env = "production"
  description = "CAFFe Zeit - Eine Website rund um Cloud Adaption"
  keywords = ["Cloud", "Azure", "Blog", "Adoption", "Cloud Adoption Framework"]
  author = "Niels Ophey"
  
  # Theme-spezifische Einstellungen
  DateFormat = "02. January 2006"
  defaultTheme = "auto" # auto, light, dark
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false
  
  # Suche aktivieren
  ShowSearchPage = true
  ShowFullTextinRSS = false

# Cover Image Konfiguration - Globale Einstellungen
[params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false
  responsiveImages = true

# Home Page Konfiguration - Clean & Professional
[params.homeInfoParams]
  Title = "Willkommen!"
  Content = """
  Dieser kleine Blog möchte über Fragen und Herausforderungen sprechen, 
  die Organisationen auf Ihrer Cloud Reise haben und erleben. Alle drei Aspekte einer solchen Reise spielen eine Rolle. 
  Veränderungen für Menschen, für Prozesse aber natürlich auch alles Rund um Cloud Technologie. 
  Technologie beutet in dem Kontext primär Microsoft Cloud Technologie.
  """

# Profile Mode (Alternative zur homeInfoParams)
[params.profileMode]
  enabled = false
  title = "Niels Ophey"
  subtitle = "technology Strategy & Cloud Enthusiast"
  imageUrl = "/images/profile.jpg"
  imageTitle = "Profilbild"
  imageWidth = 150
  imageHeight = 150
  
  [[params.profileMode.buttons]]
    name = "Blog Posts"
    url = "/posts"
  [[params.profileMode.buttons]]
    name = "Archiv"
    url = "/archives"
  [[params.profileMode.buttons]]
    name = "Suchen"
    url = "/search"

# Social Media Icons
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/CAFExpert"
[[params.socialIcons]]
  name = "X"
  url = "https://x.com/nielsophey"
[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/nielsophey"
[[params.socialIcons]]
  name = "email"
  url = "mailto:niels@ophey.net"

# Navigation Menu - Clean Icons
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "archives"
    name = "Archiv"
    url = "/archives/"
    weight = 30
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40
  [[menu.main]]
    identifier = "search"
    name = "Suchen"
    url = "/search/"
    weight = 50

# Markup Konfiguration
[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Output Formate
[outputs]
  home = ["HTML", "RSS", "JSON"]
